#ifndef SYSCALL_H_
#define SYSCALL_H_

enum syscall_code {
    //FILES
    SYSCALL_READ=0,
    SYSCALL_READBUFF,
    SYSCALL_WRITE,
    SYSCALL_WRITEBUFF,
    SYSCALL_OPEN,
    SYSCALL_CLOSE,
    SYSCALL_SEEK, 
    SYSCALL_FSIZE, 
    SYSCALL_OPENDIR,
    SYSCALL_READDIR,
    SYSCALL_CLOSEDIR,
    //MALLOC
    SYSCALL_MALLOC,
    SYSCALL_FREE ,
    //TASK
    SYSCALL_CREATETASK,
    SYSCALL_DELETETASK,
    SYSCALL_PID,
    SYSCALL_GETPID,
    SYSCALL_YIELD,
    SYSCALL_WAIT,
    SYSCALL_SLEEP,
    SYSCALL_EXIT,
    SYSCALL_KILL,
    //SERIAL
    SYSCALL_PRINTSTR,
    SYSCALL_PRINTCHAR,
    SYSCALL_EXIT2,
    TRAP_CALL=0x3127,
    TRAP_RET=0x2731
};

void syscall_handler(uint32_t code);
void svc_handler();
#endif